# Default values for rails.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: r6by/rails-hello
  tag: 0.1.0
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - name: myRegistryKeySecretName

nameOverride: ""
fullnameOverride: ""

## Configure standard environment variables.
## Ref: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
envs:
  # - name: EXAMPLE_SIMPLE_STRING
  #   value: foo
  # - name: EXAMPLE_FROM_SECRET
  #   valueFrom:
  #     secretKeyRef:
  #       name: auth
  #       key: password

## Configure dynamic environment variables with Chart template expressions.
##
## In order to allow template values (setting ENV vars from secrets, etc) the
## deployment template uses "tpl". Note the YAML block style literal ("|") must
## be used per the example below.
##
## Because of this, Helm's deep merging on values will treat this as one string
## so you will need to repeat the entire previous block with any changes. This
## is fragile, but the only way to configure dynamic environment values in Helm
## v2.
## Therefore, in order to keep overriding values simple, the 'envs'
## configuration above should be used for simple environemnt variables - when
## dynamic, templated expressions are not required.
##
envsTemplate: |-
  # - name: EXAMPLE_TEMPLATE_CONFIG_VALUE
  #   value: {{ .Values.config.example | quote }}
  # - name: EXAMPLE_TEMPLATE_RELEASE_VALUE
  #   value: {{ .Release.Namespace }}
  # - name: EXAMPLE_TEMPLATE_FROM_SECRET
  #   valueFrom:
  #     secretKeyRef:
  #       name: {{ if .Values.config.existingSecret }}{{ .Values.config.existingSecret }}{{- else }}{{ include "rails.fullname" . }}{{- end }}
  #       key: password

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: rails.test
      paths: []

  tls: []
  #  - secretName: rails-tls
  #    hosts:
  #      - rails.test

## To-do: Temporarily comment these out in order to use other handlers. The
## underlying issue is that Helm overwrite null feature I indtroduced in
## https://github.com/helm/helm/pull/2648 does not deep merge.
##
## Follow issue at: https://github.com/helm/helm/pull/5185
##
# # Override livenessProbe.
# livenessProbe:
#   httpGet:
#     path: /
#     port: http
#
# # Override readinessProbe.
# readinessProbe:
#   httpGet:
#     path: /
#     port: http

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
