apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rails.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rails.name" . }}
    helm.sh/chart: {{ include "rails.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rails.name" . }}
