{{- $fullname := include "service.fullname" . -}}
{{- $labels := include "service.labels" . -}}
{{- $serviceAccountName := include "service.serviceAccountName" . -}}
{{- $image := .Values.image.repository -}}
{{- $tag := .Values.image.tag | default .Chart.AppVersion -}}
{{- $imagePullPolicy := .Values.image.imagePullPolicy -}}
{{- $parentEnvKeyValue := .Values.envKeyValue -}}
{{- $parentEnv := .Values.env -}}
{{- $datadog := .Values.datadog -}}
{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullname }}-{{ .name }} 
  labels:
    {{- $labels | nindent 4 }}
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
          {{- with $datadog }}
            tags.datadoghq.com/env: {{ .env }}
            tags.datadoghq.com/service: {{ .service }}
            tags.datadoghq.com/version: {{ .version | quote }}
          {{- end }}
        spec:
          serviceAccountName: {{ $serviceAccountName }}
          containers:
          - image: "{{ .image.repository | $image }}:{{ .image.tag | $tag }}"
            imagePullPolicy: {{ $imagePullPolicy }}
            name: {{ .name }}
            env:
            {{- if .useParentEnv }}
            {{- range $key, $value := $parentEnvKeyValue }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- with $parentEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
            {{- with .env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $datadog }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            {{- end }}
            {{- if .envFromSecret }}
            envFrom:
            - secretRef:
                name: {{ .envFromSecret }}
            {{- end }}
            securityContext:
              {{- toYaml .securityContext | nindent 14 }}
            {{- if .command }}
            command: 
              {{- toYaml .command | nindent 14 }}
            {{- end }}
            {{- with .args }}
            args:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            resources:
              {{- toYaml .resources | nindent 14 }} 
          restartPolicy: {{ .restartPolicy | default "OnFailure" }}
  schedule: {{ .schedule | quote }}
{{- end }}
