{{- $fullname := include "service.fullname" . -}}
{{- $labels := include "service.labels" . -}}
{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullname }}-{{ .name }} 
  labels:
    {{- $labels | nindent 4 }}
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
        spec:
          {{- with .serviceAccount }}
          {{- if hasKey . "name" }}
          serviceAccountName: {{ .name }}
          {{- end }}
          {{- end }}
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            name: {{ .name }}
            {{- with .env }}
            env:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            securityContext:
              {{- toYaml .securityContext | nindent 14 }}
            {{- if .command }}
            command: {{ .command }}
            {{- end }}
            {{- with .args }}
            args:
              {{- toYaml . | nindent 14 }}
              {{- end }}
          {{- with .restartPolicy }}
          restartPolicy: {{ . }}
          {{- end }}
          resources:
            {{- toYaml .resources | nindent 14 }}
  schedule: {{ .schedule }}
{{- end }}
