{{- if .Values.autoscaler.enabled }}
apiVersion: autoscaler/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "service.fullname" . }}
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  metrics:
  {{- if .Values.autoscaler.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaler.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
