{{- $image := .Values.image.repository -}}
{{- $tag := .Values.image.tag -}}
{{- $imagePullPolicy := .Values.image.pullPolicy -}}
{{- $datadog := .Values.datadog -}}
{{- $otel := .Values.otel -}}
{{- $securityContext := .Values.securityContext -}}
{{- $parentEnvKeyValue := .Values.envKeyValue -}}
{{- $parentEnv := .Values.env -}}
{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
spec:
  {{- if .ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- with $datadog }}
        {{- if and .service .env }}
        tags.datadoghq.com/env: {{ .env }}
        tags.datadoghq.com/service: {{ .service }}
        tags.datadoghq.com/version: {{ .version | quote }}
        {{- end }}
        {{- end }}
        {{- with $otel }}
        {{- if and .service .env }}
        tags.datadoghq.com/env: {{ .env }}
        tags.datadoghq.com/service: {{ .service }}
        tags.datadoghq.com/version: {{ .version | quote }}
        {{- end }}
        {{- end }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image | default $image }}:{{ .tag | default $tag }}"
          imagePullPolicy: {{ $imagePullPolicy }}
          command:
            {{- toYaml .command | nindent 12 }}
          env:
            {{- if .useParentEnv }}
            {{- range $key, $value := $parentEnvKeyValue }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- with $parentEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $datadog }}
            {{- if and .service .env }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            {{- end }}
            {{- end }}
            {{- with $otel }}
            {{- if and .service .env }}
              - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_ENV
              value: {{ .env }}
            - name: OTEL_SERVICE
              value: {{ .service }}
            - name: OTEL_SERVICE_NAME
              value: {{ .service }}
            - name: OTEL_VERSION
              value: {{ .version | quote }}
            - name: OTEL_JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.namespace.name=$(OTEL_NAMESPACE),deployment.environment=$(OTEL_ENV),service.version=$(OTEL_VERSION),k8s.job.name=$(OTEL_JOB_NAME)
            {{- end }}
            {{- end }}
          {{- if .envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .envFromSecret }}
          {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          securityContext:
            {{- toYaml $securityContext | nindent 12 }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .persistentVolumeClaims }}
          persistentVolumeClaims:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: {{ .restartPolicy | default "OnFailure" }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 4
{{- end }}
