{{- if .Values.keda.enabled -}}
apiVersion: "keda.sh/v1alpha1"
kind: ScaledObject
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "service.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  {{- if .Values.keda.fallback }}
  fallback:
    failureThreshold: {{ .Values.keda.fallback.failureTreshold}}
    replicas: {{ .Values.keda.fallback.replicas }}
  {{- end }}
  {{- if .Values.keda.advanced }}
  advanced:  # https://keda.sh/docs/2.8/concepts/scaling-deployments/#advanced
    restoreToOriginalReplicaCount: {{ .Values.keda.advanced.restoreToOriginalReplicaCount }}
    {{- if .Values.keda.advanced.behavior }}
    horizontalPodAutoscalerConfig:
      behavior:
      {{- with .Values.keda.behavior }}
      {{- toYaml . | indent 8 }}
      {{- end }}
    {{- end }}
  {{- end }}
  triggers:  # https://keda.sh/docs/2.8/scalers/
  {{- with .Values.keda.triggers }}
  {{- toYaml . | indent 4 }}
  {{- end }}
{{- end }}