apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
{{- if .Values.podDisruptionBudget }}
  {{- with .Values.podDisruptionBudget }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- else }}
  maxUnavailable: 25%
{{- end }}
  selector:
    matchLabels:
    {{- if .Values.service.selectorLabelOverride }}
      {{- with .Values.service.selectorLabelOverride }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- else }}
      {{- include "service.selectorLabels" . | nindent 6 }}
    {{- end }}
