{{- if .Values.pre_release_job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "service.fullname" . }}-pre-release-job
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- with .Values.datadog }}
    tags.datadoghq.com/env: {{ .env }}
    tags.datadoghq.com/service: {{ .service }}
    tags.datadoghq.com/version: {{ .version | quote }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "service.fullname" . }}-pre-release-job
      labels:
        {{- include "service.labels" . | nindent 4 }}
        {{- with .Values.datadog }}
        tags.datadoghq.com/env: {{ .env }}
        tags.datadoghq.com/service: {{ .service }}
        tags.datadoghq.com/version: {{ .version | quote }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "service.fullname" . }}-pre-release-job
          image: "{{ .Values.pre_release_job.image.repository }}:{{ .Values.pre_release_job.image.tag }}"
          imagePullPolicy: {{ .Values.pre_release_job.image.pullPolicy }}
          command:
          {{- with .Values.pre_release_job.command }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.pre_release_job.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.datadog }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          {{- end }}
  backoffLimit: 1
{{- end }}
