{{- range .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .claimName }}
spec:
  accessModes: {{ .storageClass.accessModes }}
  storageClassName: {{ .storageClass.name }}
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
