{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- if .Values.metadata.namespace }}
  namespace: {{ .Values.metadata.namespace }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.service.additionalPort }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- if .Values.service.selectorLabelOverride }}
      {{- with .Values.service.selectorLabelOverride }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- else }}
      {{- include "service.selectorLabels" . | nindent 4 }}
    {{- end }}
{{- end }}
