{{- if .Values.verticalpodautoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- if .Values.metadata }}
  {{- if .Values.metadata.namespace }}
  namespace: {{ .Values.metadata.namespace }}
  {{- end }}
  {{- end }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "service.fullname" . }} 
  updatePolicy:
    updateMode: 'Off'
{{- end }}
