{{- if .Values.harness.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  gateways:
    - mesh
  hosts:
    - {{ include "service.fullname" . }}
  http:
    - route:
        - destination:
            host: {{ include "service.fullname" . }}
            port:
              number: {{ .Values.configmap.PORT }}
{{- end }}
