{{ if .Values.harness.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "service.fullname" . }}-restricted
  namespace: {{ .Values.metadata.namespace }}
spec:
  gateways:
    - istio-system/restricted-ingress-gateway
  hosts:
    - {{ .Values.virtualservice_restricted.host }}
  http:
    - route:
        - destination:
            host: {{ include "service.fullname" . }}
            port:
              number: {{ .Values.configmap.PORT }}
{{ end }}
