apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalyr.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "scalyr.name" . }}
    helm.sh/chart: {{ include "scalyr.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  k8s_cluster: {{ .Values.scalyr.config.k8sCluster }}
  {{ if .Values.scalyr.config.scalyrServer }}
  scalyr_server: {{ .Values.scalyr.config.scalyrServer }}
  {{ end }}
  {{ if .Values.scalyr.config.k8sEventsDisable }}
  k8s_events_disable: {{ .Values.scalyr.config.k8sEventsDisable }}
  {{ end }}
---
{{ if .Values.scalyr.config.agentD.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalyr.fullname" . }}-config-agent-d
  labels:
    app.kubernetes.io/name: {{ include "scalyr.name" . }}
    helm.sh/chart: {{ include "scalyr.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
  api-key.json: |+
    {
      import_vars: [ "SCALYR_API_KEY" ],
      api_key: "$SCALYR_API_KEY"
    }

  docker.json: |+
    {
      "monitors":[
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_monitor",
        }
      ]
    }

  k8s_events.json: |+
    {
      "monitors":[
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_events_monitor"
        }
      ]
    }

  scalyr-server.json: |+
    {
      "import_vars": [ { "var": "SCALYR_SERVER", "default": "https://agent.scalyr.com" } ],
      "scalyr_server": "$SCALYR_SERVER"
    }
{{ end }}
---
{{ if .Values.scalyr.config.agentJson.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalyr.fullname" . }}-config-agent-json
  labels:
    app.kubernetes.io/name: {{ include "scalyr.name" . }}
    helm.sh/chart: {{ include "scalyr.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  # Configuration for the Scalyr Agent while running on Kubernetes. For help:
  # https://www.scalyr.com/help/scalyr-agent-2

  # Note:  It is assumed that another file such as `agent.d/api-key.json` will
  # contain the api key for the user's Scalyr account.

  # No need for system and agent monitors.  The k8 plugin will gather metrics
  # on the container running the agent.
  agent.json: |
    {
      implicit_metric_monitor: false,
      implicit_agent_process_metrics_monitor: false
    }
{{ end }}
