resources:
  requests:
    cpu: 5m
  limits:
    cpu: 100m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

env:
  - name: FOO
    value: bar
  - name: POTATO
    value: potato

envKeyValue:
  ABCDEF: ghijkl
  STUFF: things
