resources:
  requests:
    cpu: 5m
  limits:
    cpu: 100m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

env:
  - name: FOO
    value: bar
  - name: POTATO
    value: potato

envKeyValue:
  ABCDEF: ghijkl
  STUFF: things
  NUMBER: 7

image:
  command:
    - nginx-debug
    - '-g'
    - 'daemon off;'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: example.internal.codecademy.com
      paths:
        - '/'

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

startupProbe:
  httpGet:
    path: /
    port: http

podLabels:
  foo: bar

annotations:
  abc: def

additionalPort:
  port: 10000
  name: potato

cronJobs:
  - name: foo
    command:  ["echo"]
    args: ["foo"]
    env:
      - name: FOO
        value: bar
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 10m
        memory: 50Mi
    schedule: "0 0 * * *"
