resources:
  requests:
    cpu: 5m
  limits:
    cpu: 100m

env:
  - name: FOO
    value: bar
  - name: POTATO
    value: potato

envKeyValue:
  ABCDEF: ghijkl
  STUFF: things
  NUMBER: 7

image:
  command:
    - nginx-debug
    - '-g'
    - 'daemon off;'

service:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: example.internal.codecademy.com
      paths:
        - '/'

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

startupProbe:
  httpGet:
    path: /
    port: http

podLabels:
  foo: bar

annotations:
  abc: def

containerPort: 80

additionalPort:
  port: 10000
  name: potato

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

cronJobs:
  - name: foo
    command: ["nginx"]
    args: ["-v"]
    useParentEnv: true
    env:
      - name: FOO
        value: bar
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 10m
        memory: 50Mi
    schedule: "* * * * *"

preReleaseJob:
  enabled: true
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent
  command: ["echo", "hello!"]
  backoffLimit: 2

hostAliases:
  - ip: 0.0.0.0
    hostnames:
      - somehost.com
  - ip: 10.0.0.0
    hostnames:
      - anotherhost.com
      - anotherhost2.com
