resources:
  requests:
    cpu: 5m
    memory: 5M
  limits:
    cpu: 100m
    memory: 10M

env:
  - name: FOO
    value: bar
  - name: POTATO
    value: potato

envKeyValue:
  ABCDEF: ghijkl
  STUFF: things
  NUMBER: 7

image:
  command:
    - nginx-debug
    - '-g'
    - 'daemon off;'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: example.internal.codecademy.com
      paths:
        - '/'

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

startupProbe:
  httpGet:
    path: /
    port: http

podLabels:
  foo: bar

annotations:
  abc: def

containerPort: 80

additionalPort:
  port: 10000
  name: potato

cronJobs:
  - name: foo
    command: ["nginx"]
    args: ["-v"]
    useParentEnv: true
    env:
      - name: FOO
        value: bar
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 10m
        memory: 50Mi
    schedule: "* * * * *"

hostAliases:
  - ip: 0.0.0.0
    hostnames:
      - somehost.com
  - ip: 10.0.0.0
    hostnames:
      - anotherhost.com
      - anotherhost2.com

keda:
  enabled: true
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicas: 1
  maxReplicas: 3
  fallback:
    failureThreshold: 5
    replicas: 1
  advanced:
    restoreToOriginalReplicaCount: true
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
    - type: memory
      metricType: Utilization
      metadata:
        value: "100"
    - type: custom
      metricType: AverageValue
      metadata:
        value: "50"
