# Create a persistent volume to test PVCs in CI
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    type: standard
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/"
